/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TalentLoginRouteImport } from './routes/talent-login'
import { Route as TalentApplicationRouteImport } from './routes/talent-application'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as SubmitTaskRouteImport } from './routes/submit-task'
import { Route as StudentRouteImport } from './routes/student'
import { Route as StaffAccessRouteImport } from './routes/staff-access'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientRouteImport } from './routes/client'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthAcceptRouteImport } from './routes/auth.accept'
import { Route as AdminStudentAffairsRouteImport } from './routes/admin.student-affairs'
import { Route as AdminRegistrarRouteImport } from './routes/admin.registrar'
import { Route as AdminPmRouteImport } from './routes/admin.pm'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminHodRouteImport } from './routes/admin.hod'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminAcademyRouteImport } from './routes/admin.academy'
import { Route as AcademyProfessionalProgramsRouteImport } from './routes/academy.professional-programs'
import { Route as AcademyDiplomaProgramsRouteImport } from './routes/academy.diploma-programs'
import { Route as AcademyCertificateProgramsRouteImport } from './routes/academy.certificate-programs'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AcademyCourseSlugRouteImport } from './routes/academy.course.$slug'
import { Route as AuthenticatedDashboardTalentRouteImport } from './routes/_authenticated/dashboard/talent'
import { Route as AuthenticatedDashboardSuperAdminRouteImport } from './routes/_authenticated/dashboard/super-admin'
import { Route as AuthenticatedDashboardStudentAffairsRouteImport } from './routes/_authenticated/dashboard/student-affairs'
import { Route as AuthenticatedDashboardRegistrarRouteImport } from './routes/_authenticated/dashboard/registrar'
import { Route as AuthenticatedDashboardPmRouteImport } from './routes/_authenticated/dashboard/pm'
import { Route as AuthenticatedDashboardInstructorRouteImport } from './routes/_authenticated/dashboard/instructor'
import { Route as AuthenticatedDashboardHodRouteImport } from './routes/_authenticated/dashboard/hod'
import { Route as AuthenticatedDashboardFinanceRouteImport } from './routes/_authenticated/dashboard/finance'
import { Route as AuthenticatedDashboardClientRouteImport } from './routes/_authenticated/dashboard/client'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedDashboardAcademyDirectorRouteImport } from './routes/_authenticated/dashboard/academy-director'
import { Route as AuthenticatedDashboardStudentIndexRouteImport } from './routes/_authenticated/dashboard/student.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'
import { Route as AuthenticatedAcademyApplySlugRouteImport } from './routes/_authenticated/academy.apply.$slug'
import { Route as AuthenticatedDashboardStudentCourseIdRouteImport } from './routes/_authenticated/dashboard/student.course.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentLoginRoute = TalentLoginRouteImport.update({
  id: '/talent-login',
  path: '/talent-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentApplicationRoute = TalentApplicationRouteImport.update({
  id: '/talent-application',
  path: '/talent-application',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitTaskRoute = SubmitTaskRouteImport.update({
  id: '/submit-task',
  path: '/submit-task',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAccessRoute = StaffAccessRouteImport.update({
  id: '/staff-access',
  path: '/staff-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VerifyRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthAcceptRoute = AuthAcceptRouteImport.update({
  id: '/auth/accept',
  path: '/auth/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentAffairsRoute = AdminStudentAffairsRouteImport.update({
  id: '/admin/student-affairs',
  path: '/admin/student-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrarRoute = AdminRegistrarRouteImport.update({
  id: '/admin/registrar',
  path: '/admin/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPmRoute = AdminPmRouteImport.update({
  id: '/admin/pm',
  path: '/admin/pm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHodRoute = AdminHodRouteImport.update({
  id: '/admin/hod',
  path: '/admin/hod',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademyRoute = AdminAcademyRouteImport.update({
  id: '/admin/academy',
  path: '/admin/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyProfessionalProgramsRoute =
  AcademyProfessionalProgramsRouteImport.update({
    id: '/professional-programs',
    path: '/professional-programs',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyDiplomaProgramsRoute = AcademyDiplomaProgramsRouteImport.update({
  id: '/diploma-programs',
  path: '/diploma-programs',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCertificateProgramsRoute =
  AcademyCertificateProgramsRouteImport.update({
    id: '/certificate-programs',
    path: '/certificate-programs',
    getParentRoute: () => AcademyRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyCourseSlugRoute = AcademyCourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const AuthenticatedDashboardTalentRoute =
  AuthenticatedDashboardTalentRouteImport.update({
    id: '/dashboard/talent',
    path: '/dashboard/talent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSuperAdminRoute =
  AuthenticatedDashboardSuperAdminRouteImport.update({
    id: '/dashboard/super-admin',
    path: '/dashboard/super-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentAffairsRoute =
  AuthenticatedDashboardStudentAffairsRouteImport.update({
    id: '/dashboard/student-affairs',
    path: '/dashboard/student-affairs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRegistrarRoute =
  AuthenticatedDashboardRegistrarRouteImport.update({
    id: '/dashboard/registrar',
    path: '/dashboard/registrar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPmRoute =
  AuthenticatedDashboardPmRouteImport.update({
    id: '/dashboard/pm',
    path: '/dashboard/pm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardInstructorRoute =
  AuthenticatedDashboardInstructorRouteImport.update({
    id: '/dashboard/instructor',
    path: '/dashboard/instructor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHodRoute =
  AuthenticatedDashboardHodRouteImport.update({
    id: '/dashboard/hod',
    path: '/dashboard/hod',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardFinanceRoute =
  AuthenticatedDashboardFinanceRouteImport.update({
    id: '/dashboard/finance',
    path: '/dashboard/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardClientRoute =
  AuthenticatedDashboardClientRouteImport.update({
    id: '/dashboard/client',
    path: '/dashboard/client',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAcademyDirectorRoute =
  AuthenticatedDashboardAcademyDirectorRouteImport.update({
    id: '/dashboard/academy-director',
    path: '/dashboard/academy-director',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentIndexRoute =
  AuthenticatedDashboardStudentIndexRouteImport.update({
    id: '/dashboard/student/',
    path: '/dashboard/student/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAcademyApplySlugRoute =
  AuthenticatedAcademyApplySlugRouteImport.update({
    id: '/academy/apply/$slug',
    path: '/academy/apply/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentCourseIdRoute =
  AuthenticatedDashboardStudentCourseIdRouteImport.update({
    id: '/dashboard/student/course/$id',
    path: '/dashboard/student/course/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/client': typeof ClientRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-access': typeof StaffAccessRoute
  '/student': typeof StudentRoute
  '/submit-task': typeof SubmitTaskRoute
  '/talent': typeof TalentRoute
  '/talent-application': typeof TalentApplicationRoute
  '/talent-login': typeof TalentLoginRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/academy/certificate-programs': typeof AcademyCertificateProgramsRoute
  '/academy/diploma-programs': typeof AcademyDiplomaProgramsRoute
  '/academy/professional-programs': typeof AcademyProfessionalProgramsRoute
  '/admin/academy': typeof AdminAcademyRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hod': typeof AdminHodRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pm': typeof AdminPmRoute
  '/admin/registrar': typeof AdminRegistrarRoute
  '/admin/student-affairs': typeof AdminStudentAffairsRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/academy-director': typeof AuthenticatedDashboardAcademyDirectorRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientRoute
  '/dashboard/finance': typeof AuthenticatedDashboardFinanceRoute
  '/dashboard/hod': typeof AuthenticatedDashboardHodRoute
  '/dashboard/instructor': typeof AuthenticatedDashboardInstructorRoute
  '/dashboard/pm': typeof AuthenticatedDashboardPmRoute
  '/dashboard/registrar': typeof AuthenticatedDashboardRegistrarRoute
  '/dashboard/student-affairs': typeof AuthenticatedDashboardStudentAffairsRoute
  '/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/dashboard/talent': typeof AuthenticatedDashboardTalentRoute
  '/academy/course/$slug': typeof AcademyCourseSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/academy/apply/$slug': typeof AuthenticatedAcademyApplySlugRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/dashboard/student/': typeof AuthenticatedDashboardStudentIndexRoute
  '/dashboard/student/course/$id': typeof AuthenticatedDashboardStudentCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/client': typeof ClientRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-access': typeof StaffAccessRoute
  '/student': typeof StudentRoute
  '/submit-task': typeof SubmitTaskRoute
  '/talent': typeof TalentRoute
  '/talent-application': typeof TalentApplicationRoute
  '/talent-login': typeof TalentLoginRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/academy/certificate-programs': typeof AcademyCertificateProgramsRoute
  '/academy/diploma-programs': typeof AcademyDiplomaProgramsRoute
  '/academy/professional-programs': typeof AcademyProfessionalProgramsRoute
  '/admin/academy': typeof AdminAcademyRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hod': typeof AdminHodRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pm': typeof AdminPmRoute
  '/admin/registrar': typeof AdminRegistrarRoute
  '/admin/student-affairs': typeof AdminStudentAffairsRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/academy-director': typeof AuthenticatedDashboardAcademyDirectorRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/client': typeof AuthenticatedDashboardClientRoute
  '/dashboard/finance': typeof AuthenticatedDashboardFinanceRoute
  '/dashboard/hod': typeof AuthenticatedDashboardHodRoute
  '/dashboard/instructor': typeof AuthenticatedDashboardInstructorRoute
  '/dashboard/pm': typeof AuthenticatedDashboardPmRoute
  '/dashboard/registrar': typeof AuthenticatedDashboardRegistrarRoute
  '/dashboard/student-affairs': typeof AuthenticatedDashboardStudentAffairsRoute
  '/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/dashboard/talent': typeof AuthenticatedDashboardTalentRoute
  '/academy/course/$slug': typeof AcademyCourseSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/academy/apply/$slug': typeof AuthenticatedAcademyApplySlugRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentIndexRoute
  '/dashboard/student/course/$id': typeof AuthenticatedDashboardStudentCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/client': typeof ClientRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-access': typeof StaffAccessRoute
  '/student': typeof StudentRoute
  '/submit-task': typeof SubmitTaskRoute
  '/talent': typeof TalentRoute
  '/talent-application': typeof TalentApplicationRoute
  '/talent-login': typeof TalentLoginRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/academy/certificate-programs': typeof AcademyCertificateProgramsRoute
  '/academy/diploma-programs': typeof AcademyDiplomaProgramsRoute
  '/academy/professional-programs': typeof AcademyProfessionalProgramsRoute
  '/admin/academy': typeof AdminAcademyRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/hod': typeof AdminHodRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pm': typeof AdminPmRoute
  '/admin/registrar': typeof AdminRegistrarRoute
  '/admin/student-affairs': typeof AdminStudentAffairsRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/verify/$id': typeof VerifyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/dashboard/academy-director': typeof AuthenticatedDashboardAcademyDirectorRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/client': typeof AuthenticatedDashboardClientRoute
  '/_authenticated/dashboard/finance': typeof AuthenticatedDashboardFinanceRoute
  '/_authenticated/dashboard/hod': typeof AuthenticatedDashboardHodRoute
  '/_authenticated/dashboard/instructor': typeof AuthenticatedDashboardInstructorRoute
  '/_authenticated/dashboard/pm': typeof AuthenticatedDashboardPmRoute
  '/_authenticated/dashboard/registrar': typeof AuthenticatedDashboardRegistrarRoute
  '/_authenticated/dashboard/student-affairs': typeof AuthenticatedDashboardStudentAffairsRoute
  '/_authenticated/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/_authenticated/dashboard/talent': typeof AuthenticatedDashboardTalentRoute
  '/academy/course/$slug': typeof AcademyCourseSlugRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/academy/apply/$slug': typeof AuthenticatedAcademyApplySlugRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/dashboard/student/': typeof AuthenticatedDashboardStudentIndexRoute
  '/_authenticated/dashboard/student/course/$id': typeof AuthenticatedDashboardStudentCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/blog'
    | '/careers'
    | '/client'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/instructor'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/signup'
    | '/sitemap.xml'
    | '/staff-access'
    | '/student'
    | '/submit-task'
    | '/talent'
    | '/talent-application'
    | '/talent-login'
    | '/team'
    | '/terms'
    | '/verify'
    | '/academy/certificate-programs'
    | '/academy/diploma-programs'
    | '/academy/professional-programs'
    | '/admin/academy'
    | '/admin/finance'
    | '/admin/hod'
    | '/admin/operations'
    | '/admin/pm'
    | '/admin/registrar'
    | '/admin/student-affairs'
    | '/auth/accept'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/verify/$id'
    | '/admin/'
    | '/dashboard/academy-director'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/finance'
    | '/dashboard/hod'
    | '/dashboard/instructor'
    | '/dashboard/pm'
    | '/dashboard/registrar'
    | '/dashboard/student-affairs'
    | '/dashboard/super-admin'
    | '/dashboard/talent'
    | '/academy/course/$slug'
    | '/lovable/email/suppression'
    | '/academy/apply/$slug'
    | '/api/public/webhooks/paystack'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/dashboard/student/'
    | '/dashboard/student/course/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/blog'
    | '/careers'
    | '/client'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/instructor'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/signup'
    | '/sitemap.xml'
    | '/staff-access'
    | '/student'
    | '/submit-task'
    | '/talent'
    | '/talent-application'
    | '/talent-login'
    | '/team'
    | '/terms'
    | '/verify'
    | '/academy/certificate-programs'
    | '/academy/diploma-programs'
    | '/academy/professional-programs'
    | '/admin/academy'
    | '/admin/finance'
    | '/admin/hod'
    | '/admin/operations'
    | '/admin/pm'
    | '/admin/registrar'
    | '/admin/student-affairs'
    | '/auth/accept'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/verify/$id'
    | '/admin'
    | '/dashboard/academy-director'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/finance'
    | '/dashboard/hod'
    | '/dashboard/instructor'
    | '/dashboard/pm'
    | '/dashboard/registrar'
    | '/dashboard/student-affairs'
    | '/dashboard/super-admin'
    | '/dashboard/talent'
    | '/academy/course/$slug'
    | '/lovable/email/suppression'
    | '/academy/apply/$slug'
    | '/api/public/webhooks/paystack'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/dashboard/student'
    | '/dashboard/student/course/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academy'
    | '/blog'
    | '/careers'
    | '/client'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/instructor'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/signup'
    | '/sitemap.xml'
    | '/staff-access'
    | '/student'
    | '/submit-task'
    | '/talent'
    | '/talent-application'
    | '/talent-login'
    | '/team'
    | '/terms'
    | '/verify'
    | '/academy/certificate-programs'
    | '/academy/diploma-programs'
    | '/academy/professional-programs'
    | '/admin/academy'
    | '/admin/finance'
    | '/admin/hod'
    | '/admin/operations'
    | '/admin/pm'
    | '/admin/registrar'
    | '/admin/student-affairs'
    | '/auth/accept'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/verify/$id'
    | '/admin/'
    | '/_authenticated/dashboard/academy-director'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/client'
    | '/_authenticated/dashboard/finance'
    | '/_authenticated/dashboard/hod'
    | '/_authenticated/dashboard/instructor'
    | '/_authenticated/dashboard/pm'
    | '/_authenticated/dashboard/registrar'
    | '/_authenticated/dashboard/student-affairs'
    | '/_authenticated/dashboard/super-admin'
    | '/_authenticated/dashboard/talent'
    | '/academy/course/$slug'
    | '/lovable/email/suppression'
    | '/_authenticated/academy/apply/$slug'
    | '/api/public/webhooks/paystack'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/dashboard/student/'
    | '/_authenticated/dashboard/student/course/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ClientRoute: typeof ClientRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InstructorRoute: typeof InstructorRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffAccessRoute: typeof StaffAccessRoute
  StudentRoute: typeof StudentRoute
  SubmitTaskRoute: typeof SubmitTaskRoute
  TalentRoute: typeof TalentRoute
  TalentApplicationRoute: typeof TalentApplicationRoute
  TalentLoginRoute: typeof TalentLoginRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRouteWithChildren
  AdminAcademyRoute: typeof AdminAcademyRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHodRoute: typeof AdminHodRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminPmRoute: typeof AdminPmRoute
  AdminRegistrarRoute: typeof AdminRegistrarRoute
  AdminStudentAffairsRoute: typeof AdminStudentAffairsRoute
  AuthAcceptRoute: typeof AuthAcceptRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-login': {
      id: '/talent-login'
      path: '/talent-login'
      fullPath: '/talent-login'
      preLoaderRoute: typeof TalentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-application': {
      id: '/talent-application'
      path: '/talent-application'
      fullPath: '/talent-application'
      preLoaderRoute: typeof TalentApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-task': {
      id: '/submit-task'
      path: '/submit-task'
      fullPath: '/submit-task'
      preLoaderRoute: typeof SubmitTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-access': {
      id: '/staff-access'
      path: '/staff-access'
      fullPath: '/staff-access'
      preLoaderRoute: typeof StaffAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof VerifyRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/accept': {
      id: '/auth/accept'
      path: '/auth/accept'
      fullPath: '/auth/accept'
      preLoaderRoute: typeof AuthAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/student-affairs': {
      id: '/admin/student-affairs'
      path: '/admin/student-affairs'
      fullPath: '/admin/student-affairs'
      preLoaderRoute: typeof AdminStudentAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrar': {
      id: '/admin/registrar'
      path: '/admin/registrar'
      fullPath: '/admin/registrar'
      preLoaderRoute: typeof AdminRegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pm': {
      id: '/admin/pm'
      path: '/admin/pm'
      fullPath: '/admin/pm'
      preLoaderRoute: typeof AdminPmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hod': {
      id: '/admin/hod'
      path: '/admin/hod'
      fullPath: '/admin/hod'
      preLoaderRoute: typeof AdminHodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academy': {
      id: '/admin/academy'
      path: '/admin/academy'
      fullPath: '/admin/academy'
      preLoaderRoute: typeof AdminAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/professional-programs': {
      id: '/academy/professional-programs'
      path: '/professional-programs'
      fullPath: '/academy/professional-programs'
      preLoaderRoute: typeof AcademyProfessionalProgramsRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/diploma-programs': {
      id: '/academy/diploma-programs'
      path: '/diploma-programs'
      fullPath: '/academy/diploma-programs'
      preLoaderRoute: typeof AcademyDiplomaProgramsRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/certificate-programs': {
      id: '/academy/certificate-programs'
      path: '/certificate-programs'
      fullPath: '/academy/certificate-programs'
      preLoaderRoute: typeof AcademyCertificateProgramsRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/course/$slug': {
      id: '/academy/course/$slug'
      path: '/course/$slug'
      fullPath: '/academy/course/$slug'
      preLoaderRoute: typeof AcademyCourseSlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/_authenticated/dashboard/talent': {
      id: '/_authenticated/dashboard/talent'
      path: '/dashboard/talent'
      fullPath: '/dashboard/talent'
      preLoaderRoute: typeof AuthenticatedDashboardTalentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/super-admin': {
      id: '/_authenticated/dashboard/super-admin'
      path: '/dashboard/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof AuthenticatedDashboardSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student-affairs': {
      id: '/_authenticated/dashboard/student-affairs'
      path: '/dashboard/student-affairs'
      fullPath: '/dashboard/student-affairs'
      preLoaderRoute: typeof AuthenticatedDashboardStudentAffairsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/registrar': {
      id: '/_authenticated/dashboard/registrar'
      path: '/dashboard/registrar'
      fullPath: '/dashboard/registrar'
      preLoaderRoute: typeof AuthenticatedDashboardRegistrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/pm': {
      id: '/_authenticated/dashboard/pm'
      path: '/dashboard/pm'
      fullPath: '/dashboard/pm'
      preLoaderRoute: typeof AuthenticatedDashboardPmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/instructor': {
      id: '/_authenticated/dashboard/instructor'
      path: '/dashboard/instructor'
      fullPath: '/dashboard/instructor'
      preLoaderRoute: typeof AuthenticatedDashboardInstructorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/hod': {
      id: '/_authenticated/dashboard/hod'
      path: '/dashboard/hod'
      fullPath: '/dashboard/hod'
      preLoaderRoute: typeof AuthenticatedDashboardHodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/finance': {
      id: '/_authenticated/dashboard/finance'
      path: '/dashboard/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof AuthenticatedDashboardFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/client': {
      id: '/_authenticated/dashboard/client'
      path: '/dashboard/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof AuthenticatedDashboardClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/academy-director': {
      id: '/_authenticated/dashboard/academy-director'
      path: '/dashboard/academy-director'
      fullPath: '/dashboard/academy-director'
      preLoaderRoute: typeof AuthenticatedDashboardAcademyDirectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student/': {
      id: '/_authenticated/dashboard/student/'
      path: '/dashboard/student'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof AuthenticatedDashboardStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academy/apply/$slug': {
      id: '/_authenticated/academy/apply/$slug'
      path: '/academy/apply/$slug'
      fullPath: '/academy/apply/$slug'
      preLoaderRoute: typeof AuthenticatedAcademyApplySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student/course/$id': {
      id: '/_authenticated/dashboard/student/course/$id'
      path: '/dashboard/student/course/$id'
      fullPath: '/dashboard/student/course/$id'
      preLoaderRoute: typeof AuthenticatedDashboardStudentCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardAcademyDirectorRoute: typeof AuthenticatedDashboardAcademyDirectorRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardClientRoute: typeof AuthenticatedDashboardClientRoute
  AuthenticatedDashboardFinanceRoute: typeof AuthenticatedDashboardFinanceRoute
  AuthenticatedDashboardHodRoute: typeof AuthenticatedDashboardHodRoute
  AuthenticatedDashboardInstructorRoute: typeof AuthenticatedDashboardInstructorRoute
  AuthenticatedDashboardPmRoute: typeof AuthenticatedDashboardPmRoute
  AuthenticatedDashboardRegistrarRoute: typeof AuthenticatedDashboardRegistrarRoute
  AuthenticatedDashboardStudentAffairsRoute: typeof AuthenticatedDashboardStudentAffairsRoute
  AuthenticatedDashboardSuperAdminRoute: typeof AuthenticatedDashboardSuperAdminRoute
  AuthenticatedDashboardTalentRoute: typeof AuthenticatedDashboardTalentRoute
  AuthenticatedAcademyApplySlugRoute: typeof AuthenticatedAcademyApplySlugRoute
  AuthenticatedDashboardStudentIndexRoute: typeof AuthenticatedDashboardStudentIndexRoute
  AuthenticatedDashboardStudentCourseIdRoute: typeof AuthenticatedDashboardStudentCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardAcademyDirectorRoute:
    AuthenticatedDashboardAcademyDirectorRoute,
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardClientRoute: AuthenticatedDashboardClientRoute,
  AuthenticatedDashboardFinanceRoute: AuthenticatedDashboardFinanceRoute,
  AuthenticatedDashboardHodRoute: AuthenticatedDashboardHodRoute,
  AuthenticatedDashboardInstructorRoute: AuthenticatedDashboardInstructorRoute,
  AuthenticatedDashboardPmRoute: AuthenticatedDashboardPmRoute,
  AuthenticatedDashboardRegistrarRoute: AuthenticatedDashboardRegistrarRoute,
  AuthenticatedDashboardStudentAffairsRoute:
    AuthenticatedDashboardStudentAffairsRoute,
  AuthenticatedDashboardSuperAdminRoute: AuthenticatedDashboardSuperAdminRoute,
  AuthenticatedDashboardTalentRoute: AuthenticatedDashboardTalentRoute,
  AuthenticatedAcademyApplySlugRoute: AuthenticatedAcademyApplySlugRoute,
  AuthenticatedDashboardStudentIndexRoute:
    AuthenticatedDashboardStudentIndexRoute,
  AuthenticatedDashboardStudentCourseIdRoute:
    AuthenticatedDashboardStudentCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AcademyRouteChildren {
  AcademyCertificateProgramsRoute: typeof AcademyCertificateProgramsRoute
  AcademyDiplomaProgramsRoute: typeof AcademyDiplomaProgramsRoute
  AcademyProfessionalProgramsRoute: typeof AcademyProfessionalProgramsRoute
  AcademyCourseSlugRoute: typeof AcademyCourseSlugRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyCertificateProgramsRoute: AcademyCertificateProgramsRoute,
  AcademyDiplomaProgramsRoute: AcademyDiplomaProgramsRoute,
  AcademyProfessionalProgramsRoute: AcademyProfessionalProgramsRoute,
  AcademyCourseSlugRoute: AcademyCourseSlugRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface VerifyRouteChildren {
  VerifyIdRoute: typeof VerifyIdRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyIdRoute: VerifyIdRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ClientRoute: ClientRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InstructorRoute: InstructorRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffAccessRoute: StaffAccessRoute,
  StudentRoute: StudentRoute,
  SubmitTaskRoute: SubmitTaskRoute,
  TalentRoute: TalentRoute,
  TalentApplicationRoute: TalentApplicationRoute,
  TalentLoginRoute: TalentLoginRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRouteWithChildren,
  AdminAcademyRoute: AdminAcademyRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHodRoute: AdminHodRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminPmRoute: AdminPmRoute,
  AdminRegistrarRoute: AdminRegistrarRoute,
  AdminStudentAffairsRoute: AdminStudentAffairsRoute,
  AuthAcceptRoute: AuthAcceptRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AdminIndexRoute: AdminIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
